### ISSUE TITLE
Polyfill not included in published browser build

### ISSUE THREAD

**Issue by stevelacy** [awslabs/aws-crt-nodejs#103]
The `polyfill.js` file is required here: https://github.com/awslabs/aws-crt-nodejs/blob/master/lib/browser/http.ts#L13
But not found in the published npm module:
```
$ tree node_modules/aws-crt/dist.browser/browser

├── aws_iot.d.ts
├── aws_iot.js
├── aws_iot.js.map
├── crypto.d.ts
├── crypto.js
├── crypto.js.map
├── error.d.ts
├── error.js
├── error.js.map
├── http.d.ts
├── http.js
├── http.js.map
├── io.d.ts
├── io.js
├── io.js.map
├── mqtt.d.ts
├── mqtt.js
├── mqtt.js.map
├── trie.d.ts
├── trie.js
├── trie.js.map
├── ws.d.ts
├── ws.js
└── ws.js.map
```

**Comment by Doff3n** [comment]
I have the same problem. Only .ts files are included in tsconfig.browser.json.

If I manually include polyfill.js I also find that Create React app cannot resolve @awscrt/io.

**Comment by stevelacy** [comment]
@Doff3n Yeah found that issue as well, quick hack is to remove the `@awscrt/io` and replace it with `../io` then run tsc

**Comment by justinboswell** [comment]
This has been fixed by the latest commit. We will roll a new version ASAP.
