### ISSUE TITLE
@awscrt/* Aliases not being resolved at compile time

### ISSUE THREAD

**Issue by salami-art** [awslabs/aws-crt-nodejs#117]
**Environment**
- Mac OS Mojave
- ` $ node -v : v14.7.0`
- ` $ rails -v : Rails 5.2.4.3`
- ` $ yarn -v : 1.22.4`

package.json: 

```
{
  "name": "testapp",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "5.1.1",
    "aws-crt": "^1.1.11"
  },
  "devDependencies": {
    "webpack-dev-server": "^3.11.0"
  }
}
```

**Steps to reproduce (I am using Ruby on Rails with webpacker)**

1. ` rails new testapp --webpack`
2. `cd testapp && bundle exec rails webpacker:install`
3. `yarn add aws-crt`
4. In `app/javascript/packs/application.js` write:
```js
import { mqtt, CrtError, io } from "aws-crt";
const client_bootstrap = new io.ClientBootstrap();
console.log(client_bootstrap)
``` 
5. run `./bin/webpack-dev-server `

For me this results in the following error:

`Can't resolve '@awscrt/io' in 'testapp/node_modules/aws-crt/dist.browser/browser'`

It seems that the aliases defined inside tsconfig.browser.json are not being properly read and my bundle won't compile. I don't know if this depends on my configuration. I will provide more information if needed.

**Comment by pickfire** [comment]
See https://github.com/awslabs/aws-crt-nodejs/pull/112

**Comment by bretambrose** [comment]
https://github.com/awslabs/aws-crt-nodejs/pull/118 should include the fix for this

**Comment by pickfire** [comment]
@bretambrose Can we create a release to include this fix? Otherwise we need to fallback to an older version in order to use it.

**Comment by InspectorGadget** [comment]
Yes, I agree with @pickfire. @bretambrose Please initiate the release, as I am locked into using a very old version of the Package.

**Comment by bretambrose** [comment]
We are having some CI/CD issues that is delaying this release.
