### ISSUE TITLE
Documentation is confusing and lacks working links between pages

### ISSUE THREAD

**Issue by mangelino** [awslabs/aws-crt-nodejs#128]
The documentation does not provide an overview of the different modules and their functionality. For example, there is a flat list of 10+ `constructor` methods without any way to know what they refer to. Links placeholders are not replaced with the actual link.

**Comment by bretambrose** [comment]
An initial doc pass corrected these issues last year.  We have another one in progress that updates to a current version of typescript/typedoc that I think should improve things further.
