### ISSUE TITLE
Browser: Cannot read property 'messageId' of

### ISSUE THREAD

**Issue by martinzak-zaber** [awslabs/aws-crt-nodejs#148]
Hello,

I tried to integrate the library as a replacement for the older aws-iot-sdk. Unfortunately, I am unable to publish messages in a browser. There is an internal callback called, but it looks like the arguments are not passed. The callback then fails when trying to access the packet (argument). Please see the screenshot of the corresponding debugging session.

![spot1](https://user-images.githubusercontent.com/48802908/100042693-d8d8f500-2dc0-11eb-8b85-3cde32623015.png) Callback about the be called. Notice that the object with messageId is actually there but the callback is empty.

![spot2](https://user-images.githubusercontent.com/48802908/100042732-ec845b80-2dc0-11eb-9f78-237f0629c88f.png)
The actual code of the callback that tries to access messageId and fails.

Thank you for investigating.

**Comment by cyuste** [comment]
Also experiencing this error, however, catching and ignoring it "solves" the issue

**Comment by bretambrose** [comment]
Fix has been released in v1.13.0.  v2 SDK release to follow shortly.
