### ISSUE TITLE
No prebuilt binary for ARM

### ISSUE THREAD

**Issue by frankrowe** [awslabs/aws-crt-nodejs#150]
Are there plans to have a prebuilt binary for ARM? I understand it can be built from source, but my Raspberry Pi 3 always runs out of memory while building.

**Comment by JonathanHenson** [comment]
Yes! We just haven’t done it yet. I’ll make sure it’s prioritized on the backlog.

**Comment by frankrowe** [comment]
> Yes! We just haven’t done it yet. I’ll make sure it’s prioritized on the backlog.

Great. Thanks.

**Comment by bretambrose** [comment]
Per aws-crt@1.8.5 and aws-iot-device-sdk-v2@1.5.5 we now bundle pre-built linux aarch64 binaries. This hopefully addresses raspberry pi 4/3 issues.

**Comment by PanMan** [comment]
This still doesn't work for arm32 bit.
