### ISSUE TITLE
Error TS1192 when compiling with TypeScript

### ISSUE THREAD

**Issue by iconara** [awslabs/aws-crt-nodejs#159]
When using this library (v1.3.4) from TypeScript (v3.8.3 and v4.1.2 tested) I get the following errors:

```
node_modules/aws-crt/dist/native/auth.d.ts:5:8 - error TS1192: Module '"<REDACTED>/node_modules/aws-crt/dist/native/binding"' has no default export.

5 import crt_native from './binding';
         ~~~~~~~~~~

node_modules/aws-crt/dist/native/http.d.ts:5:8 - error TS1192: Module '"<REDACTED>/node_modules/aws-crt/dist/native/binding"' has no default export.

5 import crt_native from './binding';
         ~~~~~~~~~~


Found 2 errors.
```

This can be fixed by rewriting the import as `import * as crt_native from './binding'`, but since this is generated code I don't know how to fix it.

**Comment by thanhduyvo** [comment]
This worked for me:
In tsconfig.json, add "allowSyntheticDefaultImports": true to compilerOptions

**Comment by tuscaonline** [comment]
i have the same issue in angular 12 
Can you update the aws-crt to have defaut export.
So we can allowSyntheticDefaultImports to false

**Comment by bretambrose** [comment]
I am not able to repro using more modern versions of typescript; closing absent more up-to-date repro or concerns.

**Comment by pinko-fowle** [comment]
I'm experiencing this now, with typescript 5.4.5. I've tried the `tsconfig.json` remedies suggested and more: `compilerOptions.module: "nodenext"`, `compilerOptions.allowSyntheticDefaultImports: true`, and a variety of other things. Nothing has fixed this.

I would like to be able to use `aws-crt-nodejs`. Please reopen, @bretambrose.
