### ISSUE TITLE
Unsubscribe crashes connection in browser

### ISSUE THREAD

**Issue by edzis** [awslabs/aws-crt-nodejs#165]
[Unsubscribe logic](https://github.com/awslabs/aws-crt-nodejs/blob/8f6002150ea3f2d3a2da7f73d06e671937a0106b/lib/browser/mqtt.ts#L381) expects to receive a `packet` as a result of from MQTT.js client, but that [returns only an optional error](https://github.com/mqttjs/MQTT.js/blob/928a0a4b59ea6dc195953dc72558a408edb7c456/README.md#unsubscribe).

<img width="722" alt="Screen Shot 2021-01-07 at 15 29 44" src="https://user-images.githubusercontent.com/163636/103898817-2eadf600-50fe-11eb-8abc-733805dee440.png">

```
mqtt.ts:390 Uncaught TypeError: Cannot read property 'messageId' of undefined
    at mqtt.ts:390
    at MqttClient.push../node_modules/mqtt/lib/client.js.MqttClient._handleAck (client.js:1371)
    at MqttClient.push../node_modules/mqtt/lib/client.js.MqttClient._handlePacket (client.js:417)
```

Further more this seems to close the connection as following attempts to subscribe to other topics result in `Error: Connection closed`.

**Comment by edzis** [comment]
The types indicate that packet is optional:
<img width="1070" alt="Screen Shot 2021-01-07 at 16 32 33" src="https://user-images.githubusercontent.com/163636/103904460-f8747480-5105-11eb-8ab6-f200b50111e0.png">

Yet in usage that does not show up as as such and is not treated accordingly:
<img width="767" alt="Screen Shot 2021-01-07 at 16 33 48" src="https://user-images.githubusercontent.com/163636/103904595-25288c00-5106-11eb-9834-e538a53c9776.png">

**Comment by graebm** [comment]
Fixed in latest releases of aws-crt and aws-iot-device-sdk-v2
