### ISSUE TITLE
MQTT Subscribe callback topic with wildcard

### ISSUE THREAD

**Issue by rym002** [awslabs/aws-crt-nodejs#167]
When subscribing to an MQTT topic using wildcards e.g. `mytopic/#` the topic sent to the callback is not the actual topic name where the message was received. In version 1 the topic passed to the callback was e.g `mytopic/sub1`. Now in version 2 the callback receives the subscription e.g. `mytopic/#`

Is there any way to receive the actual topic called?

**Comment by rym002** [comment]
Related to aws/aws-iot-device-sdk-js-v2#147

**Comment by bretambrose** [comment]
This should be fixed in release 1.5.1 of the v2 js SDK.
