### ISSUE TITLE
Allow to bypass stringification of `publish` payload

### ISSUE THREAD

**Issue by edzis** [awslabs/aws-crt-nodejs#171]
I am migrating our browser client from `aws-iot-device-sdk` to `aws-crt/dist.browser/browser/mqtt` and need to send a Uint8Array payload because the other end expects that. Unfortunately https://github.com/awslabs/aws-crt-nodejs/blob/8b8195cef124eeac8c8ef97affce097408df29fa/lib/browser/mqtt.ts#L328 converts the payload to a string format.

I am not aware any reasoning in favor of stringification and am not challenging that. However I would like to have a way to bypass that.

A custom implementation could be passed in `MqttConnectionConfig` or overwritten as a static function of `MqttClientConnection` or `MqttClient`.

**Comment by edzis** [comment]
And maybe you could point me to some argumentation for the use of this normalization? Maybe we are just bending the best practices with our usage.

**Comment by graebm** [comment]
Fixed in latest releases of aws-crt and aws-iot-device-sdk-v2

**Comment by graebm** [comment]
To bypass stringification pass an `ArrayBuffer`, or some `ArrayBufferView` such as `Uint8Array` or `DataView`
