### ISSUE TITLE
proxy options with auth does not work

### ISSUE THREAD

**Issue by sunhubs** [awslabs/aws-crt-nodejs#188]
Recently I am working with aws-crt and aws-iot-device-sdk-js-v2 to do aws Iot connection test behind a proxy.
If the proxy without authentication, it works; and if the proxy with authentication, it will fail.
So I go througth the codes and find one possible issue in aws-crt, please help confirm whether it should be correct.

in function aws_napi_http_proxy_options_new in source/http_connections.c, there are following snippets:
----------------
    napi_value node_port = *arg++;
    uint32_t port;
    AWS_NAPI_CALL(env, napi_get_value_uint32(env, node_port, &port), {
        napi_throw_type_error(env, NULL, "port must be a number");
        goto cleanup;
    });
    binding->native.port = (uint16_t)port;

    napi_value node_auth_method = *arg++;
    if (!aws_napi_is_null_or_undefined(env, node_auth_method)) {
        uint32_t auth_method = 0;
        AWS_NAPI_CALL(env, napi_get_value_uint32(env, node_port, &auth_method), {
            napi_throw_type_error(env, NULL, "auth_method must be a number");
            goto cleanup;
        });
        binding->native.auth_type = auth_method;
    }
----------
it seems to read node_port for auth_method, which may just copy from the code for node_port and do not change completely.
This will cause auth_method to be wrong value and the behavior is not clear.
Thanks.

**Comment by TingDaoK** [comment]
thanks for the PR, it's merged with the main line now.
