### ISSUE TITLE
Guidance: importing correct dist in browser

### ISSUE THREAD

**Issue by cyuste** [awslabs/aws-crt-nodejs#206]
First of all, I don't know if this ticket should be in this repo or in [aws-iot-device-sdk-js-v2](https://github.com/aws/aws-iot-device-sdk-js-v2)

I have a react typescript project that creates a mqtt websocket connection using credentials. My first idea was to use `aws-iot-device-sdk-js-v2` but I couldn't transpile it because the library was importing dist types from `aws-crt` instead of `dist.browser`

Then I realised that `aws-iot-device-sdk-js-v2` is only importing the modules and exporting them _as is_ so I moved to use `aws-crt` directly, but I have to import the modules like this
```
import { io, iot, mqtt} from 'aws-crt/dist.browser/browser';
```
Everything works but... it's ugly. Is there any recommended way to use these packages in the browser?

Thanks

**Comment by tuscaonline** [comment]
I have the same issue with angular 12

**Comment by croraf** [comment]
The solution for this is described in https://github.com/aws/aws-iot-device-sdk-js-v2/issues/301#issuecomment-1340119719 .

**Comment by bretambrose** [comment]
For what it's worth, react support was added here (https://github.com/awslabs/aws-crt-nodejs/pull/428) and angular support was added here (https://github.com/awslabs/aws-crt-nodejs/pull/440)
