### ISSUE TITLE
electron error Error: node_modules/aws-crt/dist/bin/darwin-x64/aws-crt-nodejs

### ISSUE THREAD

**Issue by zhex900** [awslabs/aws-crt-nodejs#209]
Hi,

I am trying to use `aws-iot-device-sdk-v2` in an electron app. 

When I run `electron-forge start` I get this error: 

```
App threw an error during load
Error: Cannot find module '/Users/jake/Code/mir-kiosk-electron/electron-kiosk/node_modules/aws-crt/dist/bin/darwin-x64/aws-crt-nodejs'
    at webpackEmptyContext (/Users/jake/Code/mir-kiosk-electron/electron-kiosk/.webpack/main/index.js:111944:10)
    at Object.<anonymous> (/Users/jake/Code/mir-kiosk-electron/electron-kiosk/.webpack/main/index.js:112436:91)
    at Object../node_modules/aws-crt/dist/native/binding.js (/Users/jake/Code/mir-kiosk-electron/electron-kiosk/.webpack/main/index.js:112445:30)

````

After some googling I fixed this by adding this to `webpack.main.config.js`

It will be good I don't have to use this. I think the problem is `binding.js` uses `__dirname`
```
  node: {
    __dirname: true, // I
  },
  target: "node", // in order to ignore built-in modules like path, fs, etc.
  externals: [nodeExternals()], 
````

The problem is I get a missing module error if I run the packaged app. I guess node_module is not packaged. 

```
Uncaught Exception:
Error: Cannot find module 'macaddress'
````

Do you have any idea as to how to fix it?

https://github.com/zhex900/mir-kiosk-electron/tree/master/electron-kiosk

**Comment by empz** [comment]
@zhex900 How did you solve this?

**Comment by zhex900** [comment]
Hi,

I made a patch. 

https://github.com/zhex900/mir-kiosk-electron/blob/node-ipc/electronKiosk/patches/aws-crt%2B1.8.0.patch

https://github.com/awslabs/aws-crt-nodejs/pull/220/commits/44faba53400fb0e993665b0fad79eb4a435fce72

By the way, this does not work in windows. `aws-crt` is not supported in electron on Windows.
