### ISSUE TITLE
Alpine linux support (currently crashes)

### ISSUE THREAD

**Issue by gugu** [awslabs/aws-crt-nodejs#244]
When I'm trying to upgrade aws-sdk-v3 monorepo to v3.2.9 my build fails with this error:

```
 FAIL  src/test/links/linksTest.ts
  ● Test suite failed to run

    Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /srv/shorturl_api/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node)

      at Runtime._loadModule (../node_modules/jest-runtime/build/index.js:1029:29)
      at Object.<anonymous> (../node_modules/aws-crt/lib/native/binding.js:40:19)
```

I run node using alpine 3.12 docker container:
`FROM node:16.8.0-alpine3.12`

**Comment by gugu** [comment]
I suggest using this module to detect MUSL instead of glibc: https://github.com/lovell/detect-libc/blob/master/README.md and fallback to build instead of using pre-built binary

**Comment by Hagriel** [comment]
the same error with alpine 3.14

**Comment by gugu** [comment]
for now `apk add gcompat` is the only solution

**Comment by piedrahitapablo** [comment]
I think I'm seeing the same error, here's a minimal example to reproduce:

```json
// package.json
{
  "name": "aws-crt-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "aws-crt": "^1.11.3"
  }
}

```

```javascript
// index.js
console.log("Started");
require('aws-crt');
console.log("Finished")
```

```
# Dockerfile
FROM node:16-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY ./index.js ./index.js

CMD [ "node", "./index.js" ]
```

```
docker build --rm -t aws-crt-test .
docker run --rm aws-crt-test
```

Changing the docker base image from `node:16-alpine` to `node:16` fixes the issue.

**Comment by TingDaoK** [comment]
we have added musl (alpine-linux) support since https://github.com/awslabs/aws-crt-nodejs/releases/tag/v1.16.0. Please check and let us know if it fixes your issue
