### ISSUE TITLE
Module Size Exploded in Latest Release

### ISSUE THREAD

**Issue by kleids** [awslabs/aws-crt-nodejs#245]
Looks like the latest version of this release bumped the install  size to almost 200mb? Something very weird going on

**Comment by dwood023** [comment]
Also have this issue. This caused our lambda function code to fail to upload due to the sheer size of this version, and forced us to rollback our use of dependent packages `aws-sdk/client-s3` and `@aws-sdk/s3-request-presigner` to 3.15.0.

**Comment by bretambrose** [comment]
This was fixed a while back (v1.10.0), then resurfaced again, and then was fixed again in the most recent release (v1.12.5)
