### ISSUE TITLE
Please use major version bumps when introducing architecture breakages

### ISSUE THREAD

**Issue by binarykitchen** [awslabs/aws-crt-nodejs#261]
In a project I had version 1.8.4, then bumped to 1.9.0 and npm installation went fine as well. 

Then later tried with 1.9.6 and kabooom, installation got stuck, times out.

Understand that since I'm on MacBook Air, ARM architecture isn't always well supported.

Took me hours to investigate which npm package caused headaches and narrowed down to this one. Respect for all your hard work, but recommend doing major version bumps whenever you introduce breaking changes. Thanks.

**Comment by bretambrose** [comment]
I believe we were iterating on the package/release process during 1.9.x.  The latest version should not have any breaking changes in it.

**Comment by TingDaoK** [comment]
Sorry about the confusion we made. We had the release message at latest [version](https://github.com/awslabs/aws-crt-nodejs/releases/tag/v1.10.0) that said `Previous versions from v1.9.3 to v1.9.8 are testing versions.`. What will you suggest the best way to make it clear when we need to publish some testing versions? I am happy to learn more about it.

**Comment by binarykitchen** [comment]
@TingDaoK don't know but definitely worth the research and test versions shouldn't be published. Always can refer to them via git tags when needed.
