### ISSUE TITLE
MQTT - Unknown Errors and warning logged

### ISSUE THREAD

**Issue by Sam1540** [awslabs/aws-crt-nodejs#292]
After mqtt.connect(), I get the following errors and warnings. There doesn't seem to be any impact and connection goes through. 

===============================================
[WARN] [2022-02-01T03:43:21Z] [00007fd07f9ce700] [socket] - id=0x7fd06c000cd0 fd=29: setsockopt() for NO_SIGNAL failed with errno 92. If you are having SIGPIPE signals thrown, you may want to install a signal trap in your application layer.
[ERROR] [2022-02-01T03:43:21Z] [00007fd07f9ce700] [socket] - id=0x7fd06c000cd0 fd=29: connect failed with error code 101.
[ERROR] [2022-02-01T03:43:21Z] [00007fd07f9ce700] [channel-bootstrap] - id=0x5eeb3c0: failed to create socket with error 1049
[WARN] [2022-02-01T03:43:21Z] [00007fd07f9ce700] [socket] - id=0x7fd06c000cd0 fd=29: setsockopt() for NO_SIGNAL failed with errno 92. If you are having SIGPIPE signals thrown, you may want to install a signal trap in your application layer.

**Comment by bretambrose** [comment]
We have a backlog item to rework the happy-eyeballs (https://en.wikipedia.org/wiki/Happy_Eyeballs) logging to not look like an error.
