### ISSUE TITLE
gcc 12 support

### ISSUE THREAD

**Issue by mikelpr** [awslabs/aws-crt-nodejs#323]
seems like compiling with GCC 12 is broken

failing compilation can be reproduced with a fedora:36 docker image (has gcc 12.1.1)
successful compilation can be reproduced with the fedora:34 image (has gcc 11.3.1)
(run `dnf install gcc g++ cmake git npm` to have the necessary userspace)

logs: https://gist.github.com/mikelpr/6fe2c6fe378dc28248578a6fe5ae645d

**Comment by mikelpr** [comment]
seems like it was fixed in https://github.com/awslabs/aws-lc/commit/038628d24feab1c4fce75c9b6a47bfa99b7c5edc

**Comment by bretambrose** [comment]
It doesn't look like a main branch release has been made with the fix yet: https://github.com/awslabs/aws-lc/pull/495

We can try to update the submodule once that happens.

**Comment by bretambrose** [comment]
Not sure when the submodule update to >= 1.1.0 was done, but this issue looks to have been addressed.
