### ISSUE TITLE
npm-force-resolutions does not support proxies

### ISSUE THREAD

**Issue by Clete2** [awslabs/aws-crt-nodejs#325]
Recently `npm-force-resolutions` was added as a `preinstall` step in this project. Unfortunately this breaks builds in environments where a corporate proxy is required.

See: https://github.com/rogeriochaves/npm-force-resolutions/issues/38

Can you provide a way to workaround `npm-force-resolutions` that works with a proxy?

**Comment by dennisc9** [comment]
This is also breaking our CI environments where we use an artifactory. This fails authentication and tries to pull from npm registry bypassing our .npmrc file all together. This should be set as a regular dependency / DevDependency or PeerDepenency.

**Comment by Clete2** [comment]
Confirmed. Thank you @sbSteveK !
