### ISSUE TITLE
aws-crt 1.12.4 is 600mb size

### ISSUE THREAD

**Issue by RanVaknin** [awslabs/aws-crt-nodejs#328]
Hi there,

Im reaching out because a customer has opened an [issue](https://github.com/aws/aws-sdk-js-v3/issues/3715) on the AWS-JS-SDK repo about the latest version of `aws-crt` being about 600mb in size.

I have reproduced the issue and confirmed that it is not an SDK related issue.
Here are [the changes](https://github.com/awslabs/aws-crt-nodejs/compare/v1.12.3...v1.12.4) between 1.12.3 and 1.12.4

Can someone please take a look at it?

Many thanks!

**Comment by sbSteveK** [comment]
Got a fix for this under review. Should be up relatively soon.

**Comment by sbSteveK** [comment]
v1.12.5 should fix this issue: https://github.com/awslabs/aws-crt-nodejs/releases/tag/v1.12.5
