### ISSUE TITLE
Websocket enters in interrupt/resume loop after for long run inactivity in browser

### ISSUE THREAD

**Issue by FedericoBiro** [awslabs/aws-crt-nodejs#359]
Hello,
we are using angular framework, the iot authentication is set on the server by using this guide https://docs.aws.amazon.com/iot/latest/developerguide/authorizing-direct-aws.html
Token is set to endure 12 h.
The connection is built in this way:
this.client = new mqtt.MqttClient();
const config = iot.AwsIotMqttConnectionConfigBuilder.new_builder_for_websocket()
                .with_clean_session(true)
                .with_client_id(client_id)
                .with_endpoint(AWS_IOT_ENDPOINT)
                .with_credentials(AWS_REGION, credentials.accessKeyId, credentials.secretAccessKey, credentials.sessionToken)
                .with_use_websockets()
                .with_reconnect_min_sec(0.5)
                .with_reconnect_max_sec(1)
                .with_keep_alive_seconds(2)
                .build();
connectionIot = client.new_connection(config);
            
We are facing a bug that happens when the browser is put in background or generally speaking when the browser lost the focus on the device (this can happens on windows/ios/android) after some time of inactivity the websocket starts to interrupt and resume very frequently and after a random time of repetitions the connection stays in this state of perpetuous loop interrupt/resumed also after bringing back the focus on the browser. This bug happens most commonly after a very long run of inactivity (like 1 hour but it can occurs also in short time like 10 minutes). Trying to disconnect and reconnect manually it does not work all the times because the new connection remains broken.
I suppose that the manual disconnect does not work properly because maybe the websocket can not send disconnect event to the server and this maybe leads to more errors.
Manual disconnect and reconnect process is done in this way: 
connectionIot.removeAllListeners();
await connectionIot.disconnect();
const config = iot.AwsIotMqttConnectionConfigBuilder.new_builder_for_websocket()
                .with_clean_session(true)
                .with_client_id(client_id)
                .with_endpoint(AWS_IOT_ENDPOINT)
                .with_credentials(AWS_REGION, credentials.accessKeyId, credentials.secretAccessKey, credentials.sessionToken)
                .with_use_websockets()
                .with_reconnect_min_sec(0.5)
                .with_reconnect_max_sec(1)
                .with_keep_alive_seconds(2)
                .build();
connectionIot = this.client.new_connection(config);

Is there a way to solve this?

**Comment by FedericoBiro** [comment]
Hello,
we tested the app with the new configuration set up that has been suggested, but it seems that the bug persists. For sure there's been an improvement since the first configuration.
Since the problem still occurs we tried to set also the with_reconnect_min_sec up to 30 seconds and the with_reconnect_max_sec up to 120 while the keep alive is set to 500 seconds and another problem pop up. With longer time configuration now when the application goes offline, we do not receive "interrupt" event until the keep alive time is reached. This means that if the network goes down we do not have any tool to understand if the websocket is still up or down. Generally speaking if the device goes back online the websocket too seems to go back online but no event are sent from the library. By the way in some cases the connection loop problem still occurs and we lose also control over connection status.

I checked in the code and i saw that parameters like [connection state](https://github.com/awslabs/aws-crt-nodejs/blob/main/lib/browser/mqtt.ts#L275)  and the control of the [reconnect chron](https://github.com/awslabs/aws-crt-nodejs/blob/main/lib/browser/mqtt.ts#L277) are set as private. At this point would not be better to set these params as public and let the control of the connection app-side?

**Comment by ashishpandey001** [comment]
@thdxr check this out. I think the issue at https://github.com/aws/aws-iot-device-sdk-js-v2/issues/418 is related to this.

**Comment by thdxr** [comment]
yeah this looks like the same issue i have seen what @FedericoBiro has reported

**Comment by jmklix** [comment]
Is this still an issue that you are seeing when running this in the browser? [This](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/418) issue was auto closed after a recommendation to bump up the keep alive to 1200. I would just like to make sure this is no longer a problem for anyone.
