### ISSUE TITLE
no mention of VC++ redist 2015 /runtime/ dependency

### ISSUE THREAD

**Issue by mikelpr** [awslabs/aws-crt-nodejs#371]
README mentions Visual Studio C++ 2015 dependency for building but doesn't mention that the user needs VC++ 2015 runtime dependency installed for applications that use aws-crt-nodejs. This is not obvious as the import of aws-crt fails with a process.dlopen error that says it couldn't find the aws-crt-nodejs library at the path it actually exists at (*/win32-x64/aws-crt-nodejs.node) and doesn't mention at all that it requires VCRUNTIME140.dll, which I found out scanning aws-crt-nodejs.node with https://github.com/lucasg/Dependencies

**Comment by jmklix** [comment]
We believe this requirement is included when specifying Visual Studio C++ 2015. Please let us know if you think any other dependencies are not clearly listed

**Comment by mikelpr** [comment]
@jmklix as I mentioned, it is only specified for **building**, not for runtime. if we were to take what is specified as build deps for runtime too, we would also be expecting npm and cmake on user's machines and that is not the case at all
