### ISSUE TITLE
Cmake variable 1 set but not found

### ISSUE THREAD

**Issue by monelgordillo** [awslabs/aws-crt-nodejs#379]
Cmake is complaining during npm install aws-crt-nodejs
![20221205_235015](https://user-images.githubusercontent.com/36521543/205971666-547f0fb8-d91d-469c-ba91-3299d0d9a083.jpg)

**Comment by graebm** [comment]
the build is failing due to the `-Werror` (Make all warnings into errors) build flag. It should build fine if that flag is removed.

It seems like this machine has `-Werror` set globally somehow.
what happens if you `echo $CFLAGS`? Is `-Werror` present? Try removing it.

**Comment by graebm** [comment]
Should be fixed in latest version 1.15.3
