### ISSUE TITLE
Buffer constructor is deprecated (node)

### ISSUE THREAD

**Issue by jaas666** [awslabs/aws-crt-nodejs#429]
The use of the Buffer constructor is [deprecated](https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/) in versions of Node > 4, but it's still [used here](https://github.com/awslabs/aws-crt-nodejs/blob/4fbf8c3b574f1c384a6537b4bd7598ac8bc9ca2f/lib/native/io.ts#L113) in this package.

Using certain parts of this package emits this warning:

> [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by bretambrose** [comment]
This has been addressed in v1.15.10
