### ISSUE TITLE
Webpack build warning

### ISSUE THREAD

**Issue by ChristopherGillis** [awslabs/aws-crt-nodejs#438]
Repeatedly seeing this warning:
```
Warning: in ../../../node_modules/aws-crt/dist/native/binding.js 59:18-31
  Critical dependency: the request of a dependency is an expression
```
<img width="769" alt="Screenshot 2023-03-23 at 11 56 08 AM" src="https://user-images.githubusercontent.com/8119548/227319640-f5721ca5-1a21-4a0a-8034-ada6b9d73bc9.png">

I see a related PR that is closed, but as of latest release, still seeing the error. https://github.com/awslabs/aws-crt-nodejs/pull/220

I have `aws-crt@1.15.13` installed as a dependency of `@aws-sdk/credential-provider-node@3.297.0`

**Comment by jmklix** [comment]
What exactly are you trying to build? Is this warning preventing you from useing this dependency?

We have the browser samples working for [aws-iot-device-sdk-js-v2](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/browser/pub_sub/README.md) with webpack, so this should be working for you

**Comment by unclejustin** [comment]
I get the same warning building with NextJS.

FWIW the aws-crt still works this warning is just cluttering up the logs.

**Comment by unclejustin** [comment]
I am able to work around this issue by suppressing the warning as described [here](https://medium.com/tomincode/hiding-critical-dependency-warnings-from-webpack-c76ccdb1f6c1).

My updated next.config.js excerpt:

```ts
const webpack = require("webpack");

/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config) => {
    config.plugins.push(
      new webpack.ContextReplacementPlugin(/\/aws-crt\//, (data) => {
        delete data.dependencies[0].critical;
        return data;
      })
    );
    return config;
  },
};

module.exports = nextConfig;

```
