### ISSUE TITLE
upgrade axios to ^1.6.4

### ISSUE THREAD

**Issue by nishikawa2410** [awslabs/aws-crt-nodejs#534]
### Describe the feature

Please upgrade to 1.6.4 or higher version.

### Use Case

axios in 1.6.0 is vulnerable to Prototype Pollution via the formDataToJSON function.
The vulnerability is reported in the following pages.
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jmklix** [comment]
Thanks for pointing this out. Testing this [PR](https://github.com/awslabs/aws-crt-nodejs/pull/535)
