### ISSUE TITLE
Bump axios to 1.7.4 to resolve vulnerability

### ISSUE THREAD

**Issue by aBurmeseDev** [awslabs/aws-crt-nodejs#567]
### Describe the bug

AWS SDK JavaScript team received a report for vulnerability in `axios` library which is a dependency of `aws-crt`, which in turn is a dependency of some SDK client packages. 

Reported in `aws-sdk-js-v3`: https://github.com/aws/aws-sdk-js-v3/issues/6381
Affected `axios` versions: [>= 1.3.2, <= 1.7.3](https://github.com/advisories/GHSA-8hc4-vh64-cxmj)
Current version used in CRT: [`^1.7.2`](https://github.com/awslabs/aws-crt-nodejs/blob/571a3c239195e621970e2c9c91adb9e97725f213/package.json#L54)

### Expected Behavior

No vulnerabilities!

### Current Behavior

```console
axios  >=1.3.2
Severity: high
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
fix available via `npm audit fix`
node_modules/axios
  aws-crt  >=1.19.0
  Depends on vulnerable versions of axios
  node_modules/aws-crt

2 high severity vulnerabilities
```

### Reproduction Steps

```console
npm install @aws-sdk/client-dynamodb

npm audit

npm ls axios

├─┬ @aws-sdk/client-dynamodb@3.629.0
│ └─┬ @aws-sdk/util-user-agent-node@3.614.0
│   └─┬ aws-crt@1.21.3
│     └── axios@1.7.3 
```

### Possible Solution

Consider bumping axios to `^1.7.4`

### aws-crt-nodejs version used

latest

### nodejs version used

20

### Operating System and version

macOS

**Comment by jmklix** [comment]
Fixed with this PR: https://github.com/awslabs/aws-crt-nodejs/pull/571
