### ISSUE TITLE
The hex value of SHA1 returned by CRT is of size 32 and not 40

### ISSUE THREAD

**Issue by trivikr** [awslabs/aws-crt-nodejs#581]
### Describe the bug

The hex value of SHA1 returned by CRT is of size 32 and not 40

### Expected Behavior

The hex value of sha1 for "hello world" should be "2aae6c35c94fcfb415dbe95f408b9ce91ee846ed"

### Current Behavior

The hex value of sha1 for "hello world" is "2aae6c35c94fcfb415dbe95f408b9"

### Reproduction Steps

```js
// test.mjs
import { crypto } from "aws-crt";
import { createHash } from "node:crypto";

const data = "hello world";

// Logs '2aae6c35c94fcfb415dbe95f408b9ce91ee846ed'
console.log(createHash("sha1").update(data).digest("hex"));

// Logs '2aae6c35c94fcfb415dbe95f408b9ce9'
console.log(Buffer.from(crypto.hash_sha1(data).buffer).toString("hex"));
```

### aws-crt-nodejs version used

1.22.0

### nodejs version used

20.17.0

### Operating System and version

macOS 14.6.1 (23G93)

**Comment by DmitriyMusatkin** [comment]
fixed in https://github.com/awslabs/aws-crt-nodejs/pull/583
