### ISSUE TITLE
The hex value of SHA256 returned by CRT is of size 32 and not 64

### ISSUE THREAD

**Issue by trivikr** [awslabs/aws-crt-nodejs#582]
### Describe the bug

The hex value of SHA256 returned by CRT is of size 32 and not 64

### Expected Behavior

The hex value of sha256 for "hello world" should be "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"

### Current Behavior

The hex value of sha256 for "hello world" is "b94d27b9934d3e08a52e52d7da7dabfa"

### Reproduction Steps

```js
// test.mjs
import { crypto } from "aws-crt";
import { createHash } from "node:crypto";

const data = "hello world";

// Logs 'b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9'
console.log(createHash("sha256").update(data).digest("hex"));

// Logs 'b94d27b9934d3e08a52e52d7da7dabfa'
console.log(Buffer.from(crypto.hash_sha256(data).buffer).toString("hex"));
```

### Additional Information/Context

Likely has the same root cause as that of sha1 in https://github.com/awslabs/aws-crt-nodejs/issues/581

### aws-crt-nodejs version used

1.22.0

### nodejs version used

20.17.0

### Operating System and version

macOS 14.6.1 (23G93)

**Comment by DmitriyMusatkin** [comment]
fixed in https://github.com/awslabs/aws-crt-nodejs/pull/583
